import { TASK_TYPE_LABELS, TASK_PRIORITY_LABELS } from "@/lib/task";

export const PLAN_DIRECTORY = ".forge/tasks";

export function buildPlanPath(taskId: string): string {
  return `${PLAN_DIRECTORY}/${taskId}.md`;
}

export interface PlanTask {
  id: string;
  title: string;
  type: string;
  priority: string;
  status: string;
  assignedAgent: string | null;
  description: string | null;
  notes: string | null;
  githubBranchName: string | null;
  githubIssueUrl: string | null;
}

export interface PlanProject {
  name: string;
  repositoryFullName: string;
}

export function buildPlanCommitMessage(taskTitle: string): string {
  return `docs(forge): add task plan for ${taskTitle}`;
}

export function generatePlanMarkdown(input: {
  task: PlanTask;
  project: PlanProject;
  generatedAt: string;
}): string {
  const { task, project, generatedAt } = input;

  const lines = [
    "# Forge Task Plan",
    "",
    "## Task",
    "",
    `**Title:** ${task.title}`,
    `**Type:** ${TASK_TYPE_LABELS[task.type] ?? task.type}`,
    `**Priority:** ${TASK_PRIORITY_LABELS[task.priority] ?? task.priority}`,
    `**Status:** ${task.status}`,
    `**Assigned agent:** ${task.assignedAgent ?? "Not assigned"}`,
    "",
    "## Project",
    "",
    `**Name:** ${project.name}`,
    `**Repository:** ${project.repositoryFullName}`,
    `**Branch:** ${task.githubBranchName ?? "Not linked"}`,
    `**Issue:** ${task.githubIssueUrl ?? "Not linked"}`,
    "",
    "## Description",
    "",
    task.description ?? "No description",
    "",
    "## Notes",
    "",
    task.notes ?? "No notes",
    "",
    "## Proposed Implementation",
    "",
    "_To be completed by a future Builder Agent._",
    "",
    "## Acceptance Criteria",
    "",
    "- The task has a dedicated branch.",
    "- The implementation should be reviewed before merging.",
    "- No production deployment should happen without manual approval.",
    "",
    "## Forge Metadata",
    "",
    `**Task ID:** ${task.id}`,
    "**Generated by:** Forge Core01",
    `**Generated at:** ${generatedAt}`,
  ];

  return lines.join("\n");
}
