import { Prisma } from "@prisma/client";
import { prisma } from "./db";

export const ACTIVITY_TYPES = [
  "project.created",
  "project.updated",
  "project.archived",
  "instruction.created",
  "agent.run.created",
  "agent.run.completed",
  "agent.run.failed",
  "task.created",
  "task.updated",
  "task.completed",
  "task.cancelled",
  "backlog.created",
  "deploy.dev.requested",
  "deploy.pro.requested",
  "repository.checked",
  "repository.linked",
  "repository.check_failed",
  "github.issue.created",
  "github.issue.checked",
  "github.issue.create_failed",
  "github.issue.check_failed",
  "github.branch.created",
  "github.branch.checked",
  "github.branch.create_failed",
  "github.branch.check_failed",
  "github.plan_commit.created",
  "github.plan_commit.updated",
  "github.plan_commit.checked",
  "github.plan_commit.create_failed",
  "github.plan_commit.check_failed",
  "github.pr.created",
  "github.pr.checked",
  "github.pr.create_failed",
  "github.pr.check_failed",
  "builder.proposal.created",
  "builder.proposal.completed",
  "builder.proposal.failed",
  "builder.commit.created",
  "builder.commit.completed",
  "builder.commit.completed_with_warnings",
  "builder.commit.failed",
  "builder.commit.checked",
  "github.pr_review.created",
  "github.pr_review.completed",
  "github.pr_review.failed",
  "github.pr.ready_for_review",
  "github.pr.ready_for_review_failed",
  "work_session.started",
  "work_session.stage_started",
  "work_session.stage_completed",
  "work_session.waiting_for_user",
  "work_session.completed",
  "work_session.completed_with_warnings",
  "work_session.failed",
  "work_session.iteration_started",
  "work_session.iteration_requested",
  "work_session.iteration_completed",
  "work_session.iteration_completed_with_warnings",
  "work_session.iteration_failed",
  "work_session.continued",
  "work_session.checks.started",
  "work_session.checks.completed",
  "work_session.checks.completed_with_warnings",
  "work_session.checks.failed",
  "work_session.checks.skipped",
  "preview.prepare_requested",
  "preview.created",
  "preview.application_reused",
  "preview.application_created",
  "preview.deployment_started",
  "preview.ready",
  "preview.failed",
  "preview.refreshed",
  "preview.not_configured",
  "preview.manual_registered",
  "preview.env_configured",
  "preview.env_skipped",
  "preview.env_failed",
  "production.prepare_requested",
  "production.review_created",
  "production.ready",
  "production.needs_changes",
  "production.blocked",
  "production.approved",
  "production.rejected",
  "production.refreshed",
  "promotion.prepare_requested",
  "promotion.preflight_passed",
  "promotion.preflight_failed",
  "promotion.ready",
  "promotion.execute_requested",
  "promotion.merge_started",
  "promotion.merged",
  "promotion.deploy_wait_started",
  "promotion.verification_started",
  "promotion.completed",
  "promotion.failed",
  "promotion.refreshed",
  "promotion.cancelled",
  "promotion.deploy_trigger_started",
  "promotion.deploy_triggered",
  "promotion.deploy_trigger_failed",
  "job.created",
  "job.started",
  "job.stage_started",
  "job.stage_completed",
  "job.completed",
  "job.failed",
  "job.stale",
  "job.recovered",
  "job.recovery_started",
  "job.recovery_completed",
  "worker.heartbeat_seen",
  "worker.marked_inactive",
  "worker.fallback_used",
] as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[number];

export async function logActivity(input: {
  projectId?: string | null;
  type: string;
  message: string;
  metadata?: Prisma.InputJsonValue;
}) {
  return prisma.activityLog.create({
    data: {
      projectId: input.projectId ?? null,
      type: input.type,
      message: input.message,
      metadata: input.metadata ?? undefined,
    },
  });
}
